"""
AURA Host Companion Agent
─────────────────────────
Runs natively on Windows (NOT in Docker) and gives AURA's DevOpsAgent
controlled access to the host machine: launching installed applications,
opening URLs in the default browser, and reading/writing/listing files
anywhere on the host filesystem.

Every request must be approved in the AURA chat UI before it reaches here
(handled by the approval_gate on "host_action" in RISKY_TOOLS) AND must
present the shared secret token configured in .env (HOST_AGENT_TOKEN).

Run with:
    pip install -r host_agent/requirements.txt
    python host_agent/main.py
"""
import os
import subprocess
import webbrowser
from pathlib import Path

from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel
import uvicorn

# Load host_agent/.env (generated by install.ps1) if present
_env_path = Path(__file__).parent / ".env"
if _env_path.exists():
    for line in _env_path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())

TOKEN = os.getenv("HOST_AGENT_TOKEN", "aura-host-secret-change-me")
PORT  = int(os.getenv("HOST_AGENT_PORT", "5678"))

app = FastAPI(title="AURA Host Companion Agent")


def check_auth(authorization: str | None):
    if authorization != f"Bearer {TOKEN}":
        raise HTTPException(status_code=401, detail="Invalid host agent token")


class OpenAppRequest(BaseModel):
    name: str


class OpenUrlRequest(BaseModel):
    url: str


class PathRequest(BaseModel):
    path: str


class WriteFileRequest(BaseModel):
    path: str
    content: str


@app.get("/health")
async def health():
    return {"status": "ok"}


@app.post("/open_app")
async def open_app(req: OpenAppRequest, authorization: str | None = Header(None)):
    check_auth(authorization)
    try:
        os.startfile(req.name)
        return {"success": True, "message": f"Launched {req.name}"}
    except Exception:
        try:
            subprocess.Popen(["cmd", "/c", "start", "", req.name], shell=False)
            return {"success": True, "message": f"Launched {req.name} via start"}
        except Exception as e:
            raise HTTPException(status_code=400, detail=str(e))


@app.post("/open_url")
async def open_url(req: OpenUrlRequest, authorization: str | None = Header(None)):
    check_auth(authorization)
    webbrowser.open(req.url)
    return {"success": True, "message": f"Opened {req.url} in default browser"}


@app.post("/list_dir")
async def list_dir(req: PathRequest, authorization: str | None = Header(None)):
    check_auth(authorization)
    p = Path(req.path).expanduser()
    if not p.exists() or not p.is_dir():
        raise HTTPException(status_code=404, detail="Directory not found")
    entries = []
    for item in sorted(p.iterdir()):
        entries.append({
            "name": item.name,
            "type": "dir" if item.is_dir() else "file",
            "size": item.stat().st_size if item.is_file() else None,
        })
    return {"path": str(p), "entries": entries}


@app.post("/read_file")
async def read_file(req: PathRequest, authorization: str | None = Header(None)):
    check_auth(authorization)
    p = Path(req.path).expanduser()
    if not p.exists() or not p.is_file():
        raise HTTPException(status_code=404, detail="File not found")
    if p.stat().st_size > 1_000_000:
        raise HTTPException(status_code=413, detail="File too large (max 1MB)")
    return {"path": str(p), "content": p.read_text(errors="replace")}


@app.post("/write_file")
async def write_file(req: WriteFileRequest, authorization: str | None = Header(None)):
    check_auth(authorization)
    p = Path(req.path).expanduser()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(req.content)
    return {"success": True, "path": str(p)}


if __name__ == "__main__":
    print(f"AURA Host Companion Agent listening on http://0.0.0.0:{PORT}")
    uvicorn.run(app, host="0.0.0.0", port=PORT)
